config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)" do # 言語切り替えに必要
    devise_for :admin, skip: [:registrations, :passwords], controllers: {
      sessions: "admin/sessions"
    }

    namespace :admin do
      root to: "homes#menu"
      resources :users, only: [:show, :index, :destroy], param: :canonical_name do
        get "followings" => "relationships#followings", as: "followings"
        get "followers" => "relationships#followers",  as: "followers"
      end
      patch "users/:canonical_name/cancel",   to: "users#cancel",   as: "cancel"
      patch "users/:canonical_name/withdraw", to: "users#withdraw", as: "withdraw"
      resources :posts, only: [:index, :show, :destroy] do
        resources :comments, only: [:destroy]
      end
      resources :categories, only: [:index, :destroy] do
        resources :counseling_rooms, only: [:index, :show, :destroy] do
          resources :opinions, only: [:destroy]
        end
      end
      get "categories/counseling_rooms/search", to: "counseling_rooms#search", as: "search_rooms"
    end

    devise_for :users, skip: [:passwords], controllers: {
      registrations: "public/registrations",
      sessions:      "public/sessions"
    }

    devise_scope :user do
      post "users/guest_sign_in", to: "public/sessions#guest_sign_in"
    end

    scope module: :public do
      root to: "homes#top"
      get "about", to: "homes#about"
      get "menu",  to: "homes#menu"
      resources :users, only: [:show, :index, :edit, :update], param: :canonical_name do
        resource :relationships, only: [:create, :destroy]
        get "insite",     to: "users#insite"
        get "followings", to: "relationships#followings"
        get "followers",  to: "relationships#followers"
        get "chat_rooms", to: "chats#index"
      end
      patch "users/:canonical_name/withdraw", to: "users#withdraw", as: "withdraw"
      get "users/:canonical_name/unsubscribe", to: "users#unsubscribe", as: "unsubscribe"
      resources :posts, only: [:new, :index, :show, :create, :edit, :update, :destroy] do
        resource :post_favorites, only: [:create, :destroy]
        resource :bookmarks, only: [:create, :destroy]
        resources :comments, only: [:create, :destroy] do
          resource :comment_favorites, only: [:create, :destroy]
        end
        resource :map, only: [:show]
      end
      resources :categories, only: [:create, :index] do
        resources :counseling_rooms do
          resources :participations, only: [:create, :destroy, :update]
          resources :opinions, only: [:create, :destroy] do
            resource :opinion_favorites, only: [:create, :destroy]
          end
        end
      end
      get "categories/counseling_rooms/search", to: "counseling_rooms#search", as: "search_rooms"
      resources :chats, only: [:show, :create, :destroy]
      resources :notifications, only: [:update]
      patch "clear_all_notifications", to: "notifications#clear_all", as: "clear_all_notifications"
      resources :inquiries, only: [:new, :create]
      post "inquiries/confirm", to: "inquiries#confirm", as: "inquiry_confirm"
      post "inquiries/back", to: "inquiries#back", as: "inquiry_back"
      get "inquiries/done", to: "inquiries#done", as: "inquiry_done"
      get "maps", to: "maps#index", as: "maps"
    end
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  include Notifiable

  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"

  has_one :notification, as: :notifiable, dependent: :destroy

  # データが作成されると直後に通知データも作成される
  after_create do
    create_notification(user_id: followed_id)
  end

  # 表示する通知メッセージを取得するメソッド
  def notification_message
    I18n.t("notifications.messages.relationship", canonical_name: follower.canonical_name)
  end

  # 通知クリック時のパス先指定のメソッド
  def notification_path(locale_params)
    user_path(follower.canonical_name, locale: locale_params)
  end
end

app/controllers/admin/relationships_controller.rb
class Admin::RelationshipsController < ApplicationController
  before_action :authenticate_admin!

  def followings
    @user = User.find_by(canonical_name: params[:user_canonical_name])
    @users = @user.followings.where(is_active: true).page(params[:page]).per(18)
  end

  def followers
    @user = User.find_by(canonical_name: params[:user_canonical_name])
    @users = @user.followers.where(is_active: true).page(params[:page]).per(18)
  end
end

app/helpers/admin/relationships_helper.rb
module Admin::RelationshipsHelper
end

app/views/admin/relationships/_links.html.erb
<div class='d-flex justify-content-around'>
  
  <%= link_to admin_user_followers_path(user.canonical_name) do %>
    <div>
      <p class='sm-font text-center mb-0'>
        <%= I18n.t('relationships.followers') %>
      </p>
      <p class='text-center'>
        <%= user.followers.count %>
      </p>
    </div>
  <% end %>
  
  <%= link_to admin_user_followings_path(user.canonical_name) do %>
    <div>
      <p class='sm-font text-center mb-0'>
        <%= I18n.t('relationships.followings') %>
      </p>
      <p class='text-center'>
        <%= user.followings.count %>
      </p>
    </div>
  <% end %>
  
</div>

app/views/admin/relationships/followers.html.erb
<p class='guide-links'>
  <%= link_to I18n.t('top_page'),         root_path, data: { turbolinks: false } %>>
  <%= link_to I18n.t('menu'),             admin_root_path %>>
  <%= link_to I18n.t('menus.users'),      admin_users_path %>>
  <%= link_to '@' + @user.canonical_name, admin_user_path(@user.canonical_name) %>>
  <%= I18n.t('relationships.index.followers') %>
</p>

<div class='section-title'><h2><%= I18n.t('relationships.index.followers') %></h2></div>

<section>

  <%= render 'admin/users/index', users: @users %>

</section>

app/views/admin/relationships/followings.html.erb
<p class='guide-links'>
  <%= link_to I18n.t('top_page'),         root_path, data: { turbolinks: false } %>>
  <%= link_to I18n.t('menu'),             admin_root_path %>>
  <%= link_to I18n.t('menus.users'),      admin_users_path %>>
  <%= link_to '@' + @user.canonical_name, admin_user_path(@user.canonical_name) %>>
  <%= I18n.t('relationships.index.followings') %>
</p>

<div class='section-title'><h2><%= I18n.t('relationships.index.followings') %></h2></div>

<section>

  <%= render 'admin/users/index', users: @users %>

</section>