config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)" do # 言語切り替えに必要
    devise_for :admin, skip: [:registrations, :passwords], controllers: {
      sessions: "admin/sessions"
    }

    namespace :admin do
      root to: "homes#menu"
      resources :users, only: [:show, :index, :destroy], param: :canonical_name do
        get "followings" => "relationships#followings", as: "followings"
        get "followers" => "relationships#followers",  as: "followers"
      end
      patch "users/:canonical_name/cancel",   to: "users#cancel",   as: "cancel"
      patch "users/:canonical_name/withdraw", to: "users#withdraw", as: "withdraw"
      resources :posts, only: [:index, :show, :destroy] do
        resources :comments, only: [:destroy]
      end
      resources :categories, only: [:index, :destroy] do
        resources :counseling_rooms, only: [:index, :show, :destroy] do
          resources :opinions, only: [:destroy]
        end
      end
      get "categories/counseling_rooms/search", to: "counseling_rooms#search", as: "search_rooms"
    end

    devise_for :users, skip: [:passwords], controllers: {
      registrations: "public/registrations",
      sessions:      "public/sessions"
    }

    devise_scope :user do
      post "users/guest_sign_in", to: "public/sessions#guest_sign_in"
    end

    scope module: :public do
      root to: "homes#top"
      get "about", to: "homes#about"
      get "menu",  to: "homes#menu"
      resources :users, only: [:show, :index, :edit, :update], param: :canonical_name do
        resource :relationships, only: [:create, :destroy]
        get "insite",     to: "users#insite"
        get "followings", to: "relationships#followings"
        get "followers",  to: "relationships#followers"
        get "chat_rooms", to: "chats#index"
      end
      patch "users/:canonical_name/withdraw", to: "users#withdraw", as: "withdraw"
      get "users/:canonical_name/unsubscribe", to: "users#unsubscribe", as: "unsubscribe"
      resources :posts, only: [:new, :index, :show, :create, :edit, :update, :destroy] do
        resource :post_favorites, only: [:create, :destroy]
        resource :bookmarks, only: [:create, :destroy]
        resources :comments, only: [:create, :destroy] do
          resource :comment_favorites, only: [:create, :destroy]
        end
        resource :map, only: [:show]
      end
      resources :categories, only: [:create, :index] do
        resources :counseling_rooms do
          resources :participations, only: [:create, :destroy, :update]
          resources :opinions, only: [:create, :destroy] do
            resource :opinion_favorites, only: [:create, :destroy]
          end
        end
      end
      get "categories/counseling_rooms/search", to: "counseling_rooms#search", as: "search_rooms"
      resources :chats, only: [:show, :create, :destroy]
      resources :notifications, only: [:update]
      patch "clear_all_notifications", to: "notifications#clear_all", as: "clear_all_notifications"
      resources :inquiries, only: [:new, :create]
      post "inquiries/confirm", to: "inquiries#confirm", as: "inquiry_confirm"
      post "inquiries/back", to: "inquiries#back", as: "inquiry_back"
      get "inquiries/done", to: "inquiries#done", as: "inquiry_done"
      get "maps", to: "maps#index", as: "maps"
    end
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/counseling_room.rb
class CounselingRoom < ApplicationRecord
  has_one_attached :topic_image

  belongs_to :user
  belongs_to :category

  has_many :participations,    dependent: :destroy
  has_many :opinions,          dependent: :destroy
  has_many :related_room_tags, dependent: :destroy

  has_many :room_tags, through: :related_room_tags

  scope :latest, -> { order(created_at: :desc) }
  scope :old,    -> { order(created_at: :asc) }

  validates :topic,  presence: true, length: { maximum: 100 }, uniqueness: { scope: :category }
  validates :detail, presence: true, length: { maximum: 2000 }

  # トピック画像を指定サイズへ圧縮してからデータ表示するメソッド
  def get_topic_image(width, height)
    topic_image.variant(resize_to_limit: [width, height]).processed
  end

  # キーワード検索メソッド
  def self.search_for(content)
    CounselingRoom.where(["topic LIKE(?) OR detail LIKE(?)", "%#{content}%", "%#{content}%"])
  end

  # タグ情報を保存するためのメソッド
  def save_tags(save_tag_names)
    current_tag_names = self.room_tags.pluck(:name) unless self.room_tags.nil?
    old_tag_names = current_tag_names - save_tag_names
    new_tag_names = save_tag_names - current_tag_names
    old_tag_names.each do |old_tag_name|
      room_tag = RoomTag.find_by(name: old_tag_name)
      RelatedRoomTag.find_by(room_tag_id: room_tag.id).destroy
    end
    new_tag_names.each do |new_tag_name|
      room_tag = RoomTag.find_or_create_by(name: new_tag_name)
      self.room_tags << room_tag
    end
  end
end

app/controllers/admin/counseling_rooms_controller.rb
class Admin::CounselingRoomsController < ApplicationController
  before_action :authenticate_admin!

  def index
    @keyword = params[:keyword]
    @sort    = params[:sort]
    @category = Category.find(params[:category_id])
    @counseling_rooms = @category.counseling_rooms
    @counseling_rooms = @counseling_rooms.search_for(@keyword) if @keyword.present?
    @counseling_rooms = @counseling_rooms.latest if (@sort == "latest") || @sort.nil?
    @counseling_rooms = @counseling_rooms.old    if @sort == "old"
    @counseling_rooms = @counseling_rooms.sort_by { |room| -room.participations.where(status: true).count } if @sort == "participations_count"
    @counseling_rooms = @counseling_rooms.sort_by { |room| -room.opinions.count }                           if @sort == "opinions_count"
    @counseling_rooms = Kaminari.paginate_array(@counseling_rooms).page(params[:page]).per(20)
  end                   # sort_byで取得したデータの場合に必要な、pageメソッドの配列レシーバ対応化

  def show
    @category        = Category.find(params[:category_id])
    @counseling_room = CounselingRoom.find(params[:id])
    @participations  = @counseling_room.participations.where(status: true) # 参加承認を受けているユーザーのみ表示
    @opinions        = @counseling_room.opinions
  end

  def destroy
    CounselingRoom.find(params[:id]).destroy
    redirect_to admin_category_counseling_rooms_path(params[:category_id]), notice: I18n.t("counseling_rooms.destroy")
  end

  def search
    @sort     = params[:sort]
    @keyword  = params[:keyword]
    @tag_name = params[:tag_name]
    @tags = RoomTag.sort_by_popularity
    @counseling_rooms = CounselingRoom.includes(:room_tags)
    @counseling_rooms = @counseling_rooms.search_for(@keyword) if @keyword.present?
    @counseling_rooms = @counseling_rooms.latest               if (@sort == "latest") || @sort.nil?
    @counseling_rooms = @counseling_rooms.old                  if @sort == "old"
    @counseling_rooms = @counseling_rooms.where('room_tags.name': @tag_name) if @tag_name
    @counseling_rooms = @counseling_rooms.page(params[:normal_page]).per(20)
  end
end

app/helpers/admin/counseling_rooms_helper.rb
module Admin::CounselingRoomsHelper
end

app/views/admin/counseling_rooms/_index.html.erb
<% if counseling_rooms.any? %>

  <div class='d-flex flex-wrap justify-content-center'>
  
    <% counseling_rooms.each do |room| %>
      <%= link_to admin_category_counseling_room_path(room.category.id, room.id) do %>
        <div class='counseling-room-item'>

          <p class='overflow-hidden text-nowrap text-truncate'>
            <i class="fa-solid fa-people-roof"></i>
            <%= room.topic %>
          </p>

          <div class='text-right'>
            <i class="fa-solid fa-user-group"></i>
            <%= room.participations.where(status: true).count %>
          </div>

        </div>
      <% end %>
    <% end %>
  </div>
    
  <div class='d-flex justify-content-center mt-3'>
    <%= paginate counseling_rooms, theme: 'bootstrap-5' %>
  </div>

<% else %><!--相談室が存在しない場合-->
  
  <p class='mt-5 text-center'><%= I18n.t('counseling_rooms.index.no_exist') %></p>

<% end %>

app/views/admin/counseling_rooms/index.html.erb
<p class='guide-links'>
  <%= link_to I18n.t('top_page'),         root_path, data: { turbolinks: false } %>>
  <%= link_to I18n.t('menu'),             admin_root_path %>>
  <%= link_to I18n.t('categories.title'), admin_categories_path %>>
  <%= I18n.t('counseling_rooms.index.title') %>
</p>

<div class='section-title'><h2><%= @category.name %></h2></div>

<section>
  
  <!--検索バー-->
  <%= form_with url: admin_category_counseling_rooms_path(@category.id), method: :get, local: true do |f| %>
    <div class='row justify-content-md-end justify-content-center'>
      <div class='form-group col-md-5 col-10 mb-1'>
        <%= f.select :sort, [[I18n.t('sort.latest'), 'latest'],[I18n.t('sort.old'), 'old'],[I18n.t('sort.participations_count'), 'participations_count'],[I18n.t('sort.opinions_count'), 'opinions_count']], selected: @sort, class: 'form-control' %>
      </div>
    </div>
    <div class='row justify-content-md-end justify-content-center'>
      <div class='form-group col-md-5 col-9'>
        <%= f.text_field :keyword, value: @keyword, class: 'form-control', placeholder: I18n.t('search_blank') %>
      </div>
      <div class='form-group mt-1'>
        <%= f.submit I18n.t('search'), class: 'btn btn-sm success-btn' %>
      </div>
    </div>
  <% end %>
  
  <!--ソート切り替えリンク-->
  <p class='md-font text-center mb-0'><%= I18n.t('sort.with_display_all') %></p>
  <div class='row d-flex justify-content-center pb-2'>
    <div class='d-md-flex'>
      <p class='mb-0'>
        <%= link_to I18n.t('sort.latest'),               admin_category_counseling_rooms_path(@category.id, sort: 'latest') %>
        |<%= link_to I18n.t('sort.old'),                 admin_category_counseling_rooms_path(@category.id, sort: 'old') %>
      </p>
      <p class='mb-0'><span class='d-md-inline d-none pl-1'>|</span>
        <%= link_to I18n.t('sort.participations_count'), admin_category_counseling_rooms_path(@category.id, sort: 'participations_count') %>
      </p>
      <p class='mb-0'><span class='d-md-inline d-none pl-1'>|</span>
        <%= link_to I18n.t('sort.opinions_count'),       admin_category_counseling_rooms_path(@category.id, sort: 'opinions_count') %>
      </p>
    </div>
  </div> 

  <%= render 'admin/counseling_rooms/index', counseling_rooms: @counseling_rooms %>

</section>

app/views/admin/counseling_rooms/search.html.erb
<p class='guide-links'>
  <%= link_to I18n.t('top_page'),         root_path, data: { turbolinks: false } %>>
  <%= link_to I18n.t('menu'),             admin_root_path %>>
  <%= link_to I18n.t('categories.title'), admin_categories_path %>>
  <%= I18n.t('counseling_rooms.search.title') %>
</p>

<div class='section-title'>
  <h2>
    <% if @tag_name %>
      #<%= @tag_name %>
    <% elsif @keyword %>
      <%= '「' + @keyword + '」' %>
    <% end %>
    <%= ' ' + @counseling_rooms.count.to_s + I18n.t('counseling_rooms.search.count') %>
  </h2>
</div>

<section>
  
  <!--キーワード検索バー-->
  <%= form_with url: admin_search_rooms_path, method: :get, local: true do |f| %>
    <div class='row justify-content-md-end justify-content-center'>
      <div class='form-group d-flex col-md-5 col-9'>
        <%= f.select :sort, [[I18n.t('sort.latest'), 'latest'],[I18n.t('sort.old'), 'old']], selected: @sort, class: 'form-control' %>
        <%= f.text_field :keyword, value: @keyword, class: 'form-control', placeholder: I18n.t('search_blank') %>
      </div>
      <div class='form-group mt-1'>
        <%= f.submit I18n.t('search'), class: 'btn btn-sm success-btn' %>
      </div>
    </div>
  <% end %>
  
  <!--タグ検索バー-->
  <div class='row justify-content-md-end justify-content-center'>
    <div class='col-md-5 col-9 overflow-hidden text-nowrap text-truncate'>
      <%= render 'admin/room_tags/index', room_tags: @tags %>
    </div>
  </div>
  <%= form_with url: admin_search_rooms_path, method: :get, local: true do |f| %>
    <div class='row justify-content-md-end justify-content-center'>
      <div class='form-group col-md-5 col-9'>
        <%= f.text_field :tag_name, value: @tag_name, class: 'form-control', placeholder: I18n.t('search_tag') %>
      </div>
      <div class='form-group mt-1'>
        <%= f.submit I18n.t('search'), class: 'btn btn-sm success-btn' %>
      </div>
    </div>
  <% end %>
  
  <%= render 'admin/counseling_rooms/index', counseling_rooms: @counseling_rooms %>
  
</section>

app/views/admin/counseling_rooms/show.html.erb
<p class='guide-links'>
  <%= link_to I18n.t('top_page'),         root_path, data: { turbolinks: false } %>>
  <%= link_to I18n.t('menu'),             admin_root_path %>>
  <%= link_to I18n.t('categories.title'), admin_categories_path %>>
  <%= link_to @category.name, admin_category_counseling_rooms_path(@category.id) %>>
  <%= I18n.t('counseling_rooms.show.title') %>
</p>

<div class='section-title'>
  <h2 class='overflow-hidden text-nowrap text-truncate'>
    <%= @counseling_room.topic %>
  </h2>
</div>

<section>
  
  <p class='text-right'>
    <%= link_to I18n.t('counseling_rooms.show.destroy.btn'), 
                admin_category_counseling_room_path(@category.id, @counseling_room.id), method: :delete,
                'data-confirm' => I18n.t('counseling_rooms.show.destroy.confirmation') %>
  </p>
  
  <div class='room-detail-box my-2'>
    
    <div class='d-flex flex-wrap'>
      <% if @counseling_room.room_tags.present? %>
        <%= render 'admin/room_tags/index', room_tags: @counseling_room.room_tags %>
      <% end %>
    </div>
    
    <% if @counseling_room.topic_image.present? %>
      <div class='d-md-block d-none'>
        <%= image_tag @counseling_room.get_topic_image(400, 400) %>
      </div>
      <div class='d-md-none'>
        <%= image_tag @counseling_room.get_topic_image(224, 224) %>
      </div>
    <% end %>
    
    <h4 class='mt-3'><%= @counseling_room.topic %></h4>
    
    <p><%= @counseling_room.detail %></p>
    
  </div>
  
  <p class='text-right'>
    <i class="fa-solid fa-user-group"></i>
    <span class='mr-2'>
      <%= @participations.count %>
    </span>
    
    <i class="fa-regular fa-comment"></i>
    <span class='opinions-count mr-2'>
      <%= @opinions.count %>
    </span>
    
    <%= link_to admin_user_path(@counseling_room.user.canonical_name) do %>
      <%= I18n.t('counseling_rooms.show.creator') + @counseling_room.user.public_name %>
    <% end %>
  
  </p>
  
  <hr>
  
  <div>
    <i class="fa-solid fa-user-group"></i>
    <% @participations.each do |participation| %>
      <%= link_to admin_user_path(participation.user.canonical_name) do %>
        <%= image_tag participation.user.get_profile_image(40, 40), class: 'rounded-circle m-1' %>
      <% end %>
    <% end %>
  </div>
  
  <hr>
  
  <div class='opinions-list px-2'>
    <%= render 'admin/opinions/list', opinions: @opinions, category: @category, counseling_room: @counseling_room %>
  </div>
  
</section>