config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)" do # 言語切り替えに必要
    devise_for :admin, skip: [:registrations, :passwords], controllers: {
      sessions: "admin/sessions"
    }

    namespace :admin do
      root to: "homes#menu"
      resources :users, only: [:show, :index, :destroy], param: :canonical_name do
        get "followings" => "relationships#followings", as: "followings"
        get "followers" => "relationships#followers",  as: "followers"
      end
      patch "users/:canonical_name/cancel",   to: "users#cancel",   as: "cancel"
      patch "users/:canonical_name/withdraw", to: "users#withdraw", as: "withdraw"
      resources :posts, only: [:index, :show, :destroy] do
        resources :comments, only: [:destroy]
      end
      resources :categories, only: [:index, :destroy] do
        resources :counseling_rooms, only: [:index, :show, :destroy] do
          resources :opinions, only: [:destroy]
        end
      end
      get "categories/counseling_rooms/search", to: "counseling_rooms#search", as: "search_rooms"
    end

    devise_for :users, skip: [:passwords], controllers: {
      registrations: "public/registrations",
      sessions:      "public/sessions"
    }

    devise_scope :user do
      post "users/guest_sign_in", to: "public/sessions#guest_sign_in"
    end

    scope module: :public do
      root to: "homes#top"
      get "about", to: "homes#about"
      get "menu",  to: "homes#menu"
      resources :users, only: [:show, :index, :edit, :update], param: :canonical_name do
        resource :relationships, only: [:create, :destroy]
        get "insite",     to: "users#insite"
        get "followings", to: "relationships#followings"
        get "followers",  to: "relationships#followers"
        get "chat_rooms", to: "chats#index"
      end
      patch "users/:canonical_name/withdraw", to: "users#withdraw", as: "withdraw"
      get "users/:canonical_name/unsubscribe", to: "users#unsubscribe", as: "unsubscribe"
      resources :posts, only: [:new, :index, :show, :create, :edit, :update, :destroy] do
        resource :post_favorites, only: [:create, :destroy]
        resource :bookmarks, only: [:create, :destroy]
        resources :comments, only: [:create, :destroy] do
          resource :comment_favorites, only: [:create, :destroy]
        end
        resource :map, only: [:show]
      end
      resources :categories, only: [:create, :index] do
        resources :counseling_rooms do
          resources :participations, only: [:create, :destroy, :update]
          resources :opinions, only: [:create, :destroy] do
            resource :opinion_favorites, only: [:create, :destroy]
          end
        end
      end
      get "categories/counseling_rooms/search", to: "counseling_rooms#search", as: "search_rooms"
      resources :chats, only: [:show, :create, :destroy]
      resources :notifications, only: [:update]
      patch "clear_all_notifications", to: "notifications#clear_all", as: "clear_all_notifications"
      resources :inquiries, only: [:new, :create]
      post "inquiries/confirm", to: "inquiries#confirm", as: "inquiry_confirm"
      post "inquiries/back", to: "inquiries#back", as: "inquiry_back"
      get "inquiries/done", to: "inquiries#done", as: "inquiry_done"
      get "maps", to: "maps#index", as: "maps"
    end
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :counseling_rooms, dependent: :destroy

  scope :latest, -> { order(created_at: :desc) }
  scope :old,    -> { order(created_at: :asc) }

  validates :name, presence: true, uniqueness: true

  # キーワード検索のメソッド
  def self.search_for(content)
    Category.where("name LIKE ?", "%#{content}%")
  end
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < ApplicationController
  before_action :authenticate_admin!

  def index
    @model   = params[:model]
    @keyword = params[:keyword]
    @sort    = params[:sort]
    @categories       = Category.all
    @counseling_rooms = CounselingRoom.all
    @tags = RoomTag.sort_by_popularity
    if @model == "counseling_room"
      @counseling_rooms = @counseling_rooms.search_for(@keyword) if @keyword.present?
      @counseling_rooms = @sort == "old" ? @counseling_rooms.old : @counseling_rooms.latest
      @counseling_rooms = @counseling_rooms.page(params[:normal_page]).per(20)
      render "admin/counseling_rooms/search" # 検索対象が相談室の場合のみsearch画面へ遷移
    end
    @categories = @categories.search_for(@keyword) if @keyword.present?
    @categories = @sort == "old" ? @categories.old : @categories.latest
    @categories = @categories.page(params[:page]).per(12)
  end

  def destroy
    Category.find(params[:id]).destroy
    redirect_to request.referer, notice: I18n.t("categories.destroy.success")
  end
end

app/helpers/admin/categories_helper.rb
module Admin::CategoriesHelper
end

app/views/admin/categories/index.html.erb
<p class='guide-links'>
  <%= link_to I18n.t('top_page'), root_path, data: { turbolinks: false } %>>
  <%= link_to I18n.t('menu'),     admin_root_path %>>
  <%= I18n.t('menus.rooms') %>
</p>

<div class='section-title'><h2><%= I18n.t('categories.title') %></h2></div>

<section>
  
  <!--キーワード検索バー-->
  <%= form_with url: admin_categories_path, method: :get, local: true do |f| %>
    <div class='row justify-content-md-end justify-content-center'>
      <div class='form-group col-md-5 col-10 mb-1'>
        <%= f.select :model, [[I18n.t('categories.bars.category'), 'category'],[I18n.t('categories.bars.counseling_room'), 'counseling_room']], selected: @model, class: 'form-control' %>
        <%= f.select :sort, [[I18n.t('sort.latest'), 'latest'],[I18n.t('sort.old'), 'old']], selected: @sort, class: 'form-control' %>
      </div>
    </div>
    <div class='row justify-content-md-end justify-content-center'>
      <div class='form-group col-md-5 col-9'>
        <%= f.text_field :keyword, value: @keyword, class: 'form-control', placeholder: I18n.t('search_blank') %>
      </div>
      <div class='form-group mt-1'>
        <%= f.submit I18n.t('search'), class: 'btn btn-sm success-btn' %>
      </div>
    </div>
  <% end %>
  
  <!--タグ検索バー-->
  <div class='row justify-content-md-end justify-content-center'>
    <div class='col-md-5 col-9 overflow-hidden text-nowrap text-truncate'>
      <%= render 'admin/room_tags/index', room_tags: @tags %>
    </div>
  </div>
  <%= form_with url: admin_search_rooms_path, method: :get, local: true do |f| %>
    <div class='row justify-content-md-end justify-content-center'>
      <div class='form-group col-md-5 col-9'>
        <%= f.text_field :tag_name, class: 'form-control', placeholder: I18n.t('search_tag') %>
      </div>
      <div class='form-group mt-1'>
        <%= f.submit I18n.t('search'), class: 'btn btn-sm success-btn' %>
      </div>
    </div>
  <% end %>
  
  <!--ソート切り替えリンク-->
  <p class='md-font text-center mb-0'><%= I18n.t('sort.with_display_all') %></p>
  <div class='text-center pb-2'>
  <%= link_to I18n.t('sort.latest'), admin_categories_path(sort: 'latest') %>
  |<%= link_to I18n.t('sort.old'),   admin_categories_path(sort: 'old') %>
  </div> 
  
  <% if @categories.any? %>
  
    <div class='d-flex flex-wrap justify-content-center'>
      <% @categories.each do |category| %>
        <%= link_to admin_category_counseling_rooms_path(category.id) do %>
          <div class='category-item'>
  
            <p class='overflow-hidden text-nowrap text-truncate'>
              <%= category.name %>
            </p>
            
            <div class='text-right'>
              <i class="fa-solid fa-door-open"></i>
              <%= category.counseling_rooms.count %>
              
              <object>
                <%= link_to I18n.t('destroy'), admin_category_path(category.id), method: :delete, 
                                               'data-confirm' => I18n.t('categories.destroy.confirmation') %>
              </object>
            </div>
  
          </div>
        <% end %>
      <% end %>
    </div>
  
    <div class='d-flex justify-content-center mt-3'>
      <%= paginate @categories, theme: 'bootstrap-5' %>
    </div>
  
  <% else %><!--カテゴリが存在しない場合-->
    <p class='mt-5 text-center'><%= I18n.t('categories.index.no_exist') %></p>
  <% end %>
  
</section>