config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)" do # 言語切り替えに必要
    devise_for :admin, skip: [:registrations, :passwords], controllers: {
      sessions: "admin/sessions"
    }

    namespace :admin do
      root to: "homes#menu"
      resources :users, only: [:show, :index, :destroy], param: :canonical_name do
        get "followings" => "relationships#followings", as: "followings"
        get "followers" => "relationships#followers",  as: "followers"
      end
      patch "users/:canonical_name/cancel",   to: "users#cancel",   as: "cancel"
      patch "users/:canonical_name/withdraw", to: "users#withdraw", as: "withdraw"
      resources :posts, only: [:index, :show, :destroy] do
        resources :comments, only: [:destroy]
      end
      resources :categories, only: [:index, :destroy] do
        resources :counseling_rooms, only: [:index, :show, :destroy] do
          resources :opinions, only: [:destroy]
        end
      end
      get "categories/counseling_rooms/search", to: "counseling_rooms#search", as: "search_rooms"
    end

    devise_for :users, skip: [:passwords], controllers: {
      registrations: "public/registrations",
      sessions:      "public/sessions"
    }

    devise_scope :user do
      post "users/guest_sign_in", to: "public/sessions#guest_sign_in"
    end

    scope module: :public do
      root to: "homes#top"
      get "about", to: "homes#about"
      get "menu",  to: "homes#menu"
      resources :users, only: [:show, :index, :edit, :update], param: :canonical_name do
        resource :relationships, only: [:create, :destroy]
        get "insite",     to: "users#insite"
        get "followings", to: "relationships#followings"
        get "followers",  to: "relationships#followers"
        get "chat_rooms", to: "chats#index"
      end
      patch "users/:canonical_name/withdraw", to: "users#withdraw", as: "withdraw"
      get "users/:canonical_name/unsubscribe", to: "users#unsubscribe", as: "unsubscribe"
      resources :posts, only: [:new, :index, :show, :create, :edit, :update, :destroy] do
        resource :post_favorites, only: [:create, :destroy]
        resource :bookmarks, only: [:create, :destroy]
        resources :comments, only: [:create, :destroy] do
          resource :comment_favorites, only: [:create, :destroy]
        end
        resource :map, only: [:show]
      end
      resources :categories, only: [:create, :index] do
        resources :counseling_rooms do
          resources :participations, only: [:create, :destroy, :update]
          resources :opinions, only: [:create, :destroy] do
            resource :opinion_favorites, only: [:create, :destroy]
          end
        end
      end
      get "categories/counseling_rooms/search", to: "counseling_rooms#search", as: "search_rooms"
      resources :chats, only: [:show, :create, :destroy]
      resources :notifications, only: [:update]
      patch "clear_all_notifications", to: "notifications#clear_all", as: "clear_all_notifications"
      resources :inquiries, only: [:new, :create]
      post "inquiries/confirm", to: "inquiries#confirm", as: "inquiry_confirm"
      post "inquiries/back", to: "inquiries#back", as: "inquiry_back"
      get "inquiries/done", to: "inquiries#done", as: "inquiry_done"
      get "maps", to: "maps#index", as: "maps"
    end
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one_attached :profile_image

  with_options dependent: :destroy do
    has_many :posts
    has_many :comments
    has_many :counseling_rooms
    has_many :participations
    has_many :opinions
    has_many :post_favorites
    has_many :comment_favorites
    has_many :opinion_favorites
    has_many :bookmarks
    has_many :post_views
    has_many :active_profile_views,  class_name: "ProfileView",  foreign_key: "viewer_id"
    has_many :passive_profile_views, class_name: "ProfileView",  foreign_key: "viewed_id"
    has_many :active_relationships,  class_name: "Relationship", foreign_key: "follower_id"
    has_many :passive_relationships, class_name: "Relationship", foreign_key: "followed_id"
    has_many :entries
    has_many :chats
    has_many :notifications
  end

  has_many :bookmarked_posts, through: :bookmarks,             source: :post
  has_many :followings,       through: :active_relationships,  source: :followed
  has_many :followers,        through: :passive_relationships, source: :follower
  has_many :chat_rooms,       through: :entries, dependent: :destroy

  scope :latest, -> { order(created_at: :desc) }
  scope :old,    -> { order(created_at: :asc) }

  enum position: { beginner: 0, intermediate: 1, veteran: 2 }

  with_options presence: true do
    validates :email,          uniqueness: true
    validates :last_name
    validates :first_name
    validates :canonical_name, uniqueness: true, format: { with: /\A[a-zA-Z0-9]+\z/ }, length: { minimum: 1, maximum: 20 }
    validates :public_name
    validates :position
  end

  validates :introduction, length: { maximum: 200 }

  GUEST_USER_EMAIL = "guest@example.com"

  # プロフィール画像を指定サイズへ圧縮してからデータ表示するメソッド(画像の登録がなければデフォルト画像を表示)
  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join("app/assets/images/no_image.jpg")
      profile_image.attach(io: File.open(file_path), filename: "default-profile-image.jpg", content_type: "image/jpeg")
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end

  # ポジションによって別のcssクラスを呼び出すメソッド
  def get_class_associated_with_position
    return "position-beginner"     if position == "beginner"
    return "position-intermediate" if position == "intermediate"
    "position-veteran"
  end

  # ゲストログイン時のメソッド
  def self.guest
    find_or_create_by!(email: GUEST_USER_EMAIL) do |user|
      user.password       = SecureRandom.urlsafe_base64
      user.last_name      = "guest"
      user.first_name     = "user"
      user.public_name    = "guestuser"
      user.canonical_name = "guestuser"
      user.position       = 1
    end
  end

  # ゲストユーザーか確かめるためのメソッド
  def guest_user?
    email == GUEST_USER_EMAIL
  end

  # 相談室の参加ステータスを確認するためのメソッド
  def get_participation_status(room)
    if id == room.user_id
      I18n.t("participations.creator")
    elsif participations.exists?(counseling_room_id: room.id) && participations.find_by(counseling_room_id: room.id).status
      I18n.t("participations.participating")
    elsif participations.exists?(counseling_room_id: room.id)
      I18n.t("participations.applying")
    else
      I18n.t("participations.not_participating")
    end
  end

  # キーワード検索メソッド
  def self.search_for(content)
    User.where(["public_name LIKE(?) OR canonical_name LIKE(?) OR introduction LIKE(?)", "%#{content}%", "%#{content}%", "%#{content}%"])
  end

  # マイページでのブックマーク投稿のキーワード検索メソッド
  def search_with_bookmarks_for(content)
    self.bookmarked_posts.where(["title LIKE(?) OR caption LIKE(?) OR body LIKE(?)", "%#{content}%", "%#{content}%", "%#{content}%"])
  end

  # フォローするメソッド
  def follow(user)
    active_relationships.create(followed_id: user.id)
  end

  # フォローを外すメソッド
  def unfollow(user)
    active_relationships.find_by(followed_id: user.id).destroy
  end

  # フォローしてるか確かめるメソッド
  def following?(user)
    followings.include?(user)
  end

  # 未読のチャットがあるか確かめるメソッド
  def has_unread_chat?
    self.chat_rooms.each do |chat_room|
      chat_room.entries.each do |entry|
        if entry.user_id != self.id
          return true if entry.is_there_unread?(entry.user)
        end
      end
    end
    false
  end

  # 有効ユーザーか確認
  def active_for_authentication?
    super && is_active
  end
  
  # ユーザーがアカウント削除する際、紐付くチャットルームの相手側のEntryモデル削除
  def destroy_entries(user)
    chat_rooms.each do |room|
      room.entries.each do |entry|
        entry.destroy if entry.user_id != user.id
      end
    end
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :authenticate_admin!
  before_action :set_selected_user, except: [:index]

  def show
    @keyword    = params[:keyword]
    @prefecture = params[:prefecture]
    @sort       = params[:sort]
    @posts = @user.posts&.where(is_published: true)

    @posts = @posts.search_with_user_for(@keyword, @user) if @keyword.present?
    @posts = @posts.where(prefecture: @prefecture)        if @prefecture.present? && (@prefecture != "unspecified")
    @posts = @sort == "old" ? @posts.old : (@sort == "favorites_count" ? @posts&.sort_by { |post| -post.post_favorites.count } : @posts.latest)
    @posts = Kaminari.paginate_array(@posts).page(params[:page]).per(12)
  end        # sort_byで取得したデータの場合に必要な、pageメソッドの配列レシーバ対応化

  def index
    @keyword = params[:keyword]
    @sort    = params[:sort]
    @users = User.all # 退会済みユーザーも含め表示
    @users = @users.search_for(@keyword) if @keyword.present?
    @users = @sort == "latest" ? @users.latest : (@sort == "posts_count" ? @users.sort_by { |user| -user.posts.count } : @users.old)
    @users = Kaminari.paginate_array(@users).page(params[:page]).per(18)
  end        # sort_byで取得したデータの場合に必要な、pageメソッドの配列レシーバ対応化

  def cancel
    @user.update(is_active: true)
    redirect_to request.referer
  end

  def withdraw
    @user.update(is_active: false)
    @user.posts.update_all(is_published: false) # 公開中の投稿全て非公開に変更
    sign_out(@user)
    redirect_to request.referer
  end

  def destroy
    @user.destroy_entries(@user)
    @user.destroy
    redirect_to admin_users_path, notice: I18n.t("admin.users.destroy.notice")
  end

  private
    def set_selected_user
      @user = User.find_by(canonical_name: params[:canonical_name])
    end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/views/admin/users/_index.html.erb
<% if users.any? %><!--ユーザーが存在する場合-->

  <div class='d-flex flex-wrap justify-content-center'>

    <% users.each do |user| %> <!--各ユーザーの情報表示-->
      <%= link_to admin_user_path(user.canonical_name) do %>
        <div class='user-index-item'>

          <div class='d-flex'>

            <%= image_tag user.get_profile_image(40, 40), class: 'rounded-circle mr-2' %>

            <% unless user.is_active %>
              <span class='text-danger'><%= I18n.t('users.index.inactive') %></span>
            <% end %>

          </div>

          <p class='overflow-hidden text-nowrap text-truncate mb-0'>
            @<%= user.canonical_name %>
          </p><hr>

          <p class='overflow-hidden text-nowrap text-truncate mb-0'>
            <%= user.public_name %>
          </p>

          <p class='mb-0'>
            <span class=<%= user.get_class_associated_with_position %>>
              <%= user.position_i18n %>
            </span>
          </p>

          <p class='overflow-hidden text-nowrap text-truncate'>
            <%= user.introduction %>
          </p>

          <p class='user-index-chart-box d-flex'>
            <span class='mr-2'>
              <i class="fa-regular fa-image"></i>
              <%= user.posts.count %>
            </span>
            <span>
              <i class="fa-solid fa-handshake-angle"></i>
              <%= user.followers.count %>
            </span>
          </p>

        </div>
      <% end %>
    <% end %>
  </div>
    
  <div class='d-flex justify-content-center mt-3'>
    <%= paginate users, theme: 'bootstrap-5' %>
  </div>

<% else %><!--ユーザーが存在しない場合-->
  <p class='mt-5 text-center'><%= I18n.t('users.index.not_exist') %></p>
<% end %>

app/views/admin/users/index.html.erb
<p class='guide-links'>
  <%= link_to I18n.t('top_page'), root_path, data: { turbolinks: false } %>>
  <%= link_to I18n.t('menu'),     admin_root_path %>>
  <%=  I18n.t('menus.users') %>
</p>

<div class='section-title'><h2><%= I18n.t('users.index.title') %></h2></div>

<section>

  <!--検索バー-->
  <%= form_with url: admin_users_path, method: :get, local: true do |f| %>
    <div class='row justify-content-md-end justify-content-center'>
      <div class='form-group col-md-5 col-10 mb-1'>
        <%= f.select :sort, [[I18n.t('sort.latest'), 'latest'],[I18n.t('sort.old'), 'old'],[I18n.t('sort.posts_count'), 'posts_count']], selected: @sort, class: 'form-control' %>
      </div>
    </div>
    <div class='row justify-content-md-end justify-content-center'>
      <div class='form-group col-md-5 col-9'>
        <%= f.text_field :keyword, value: @keyword, class: 'form-control', placeholder: I18n.t('search_blank') %>
      </div>
      <div class='form-group mt-1'>
        <%= f.submit I18n.t('search'), class: 'btn btn-sm success-btn' %>
      </div>
    </div>
  <% end %>

  <!--ソート切り替えリンク-->
  <p class='md-font text-center mb-0'><%= I18n.t('sort.with_display_all') %></p>
  <div class='d-flex justify-content-center pb-2'>
    <div class='d-md-flex'>
      <p class='mb-0'>
        <%= link_to I18n.t('sort.user_latest'),  admin_users_path(sort: 'latest') %>
        |<%= link_to I18n.t('sort.user_old'),    admin_users_path(sort: 'old') %>
      </p>
      <p class='mb-0'><span class='d-md-inline d-none pl-1'>|</span>
        <%= link_to I18n.t('sort.posts_count'), admin_users_path(sort: 'posts_count') %>
      </p>
    </div>
  </div>

  <!--ユーザー一覧の表示-->
  <%= render 'admin/users/index', users: @users %>

</section>

app/views/admin/users/show.html.erb
<p class='guide-links'>
  <%= link_to I18n.t('top_page'),    root_path, data: { turbolinks: false } %>>
  <%= link_to I18n.t('menu'),        admin_root_path %>>
  <%= link_to I18n.t('menus.users'), admin_users_path %>>
  @<%= @user.canonical_name %>
</p>

<div class='section-title'><h2>@<%= @user.canonical_name %></h2></div>

<div class='admin-users-show-box py-3'><!--管理者ページにのみ表示の内容-->
  <p><%= @user.last_name + ' ' + @user.first_name %></p>
  <p><%= I18n.t('users.show.joined_date') + ' ' + @user.created_at.strftime('%Y/%m/%d') %></p>

  <% if @user.is_active %>
    <p class='text-success'><%= I18n.t('users.show.active') %></p>
    <%= link_to I18n.t('admin.users.withdraw'),  admin_withdraw_path(@user.canonical_name), method: :patch %>
  <% else %>
    <p class='text-danger'><%= I18n.t('users.show.inactive') %></p>
    <%= link_to I18n.t('admin.users.cancel'),    admin_cancel_path(@user.canonical_name),   method: :patch %>
  <% end %>

  <%= link_to I18n.t('admin.users.destroy.btn'), admin_user_path(@user.canonical_name),     method: :delete, class: 'ml-2', 'data-confirm' => I18n.t('admin.users.destroy.confirmation') %>
</div>

<section>
  <div class='row justify-content-center'>

    <div class='col-md-4'><!--ユーザー情報-->
      <p class='text-center'>
        <i class="fa-solid fa-chart-line"></i>
        <%= I18n.t('views_count.profile') %>
        <%= @user.passive_profile_views.count %>
      </p>

      <div id='shrinked-image' class='d-inline'>
        <%= image_tag @user.get_profile_image(60, 60), class: 'rounded-circle' %>
      </div>
      
      <div id='expanded-image' class='image-non-expansion'>
        <%= image_tag @user.get_profile_image(250, 250), class: 'rounded-circle' %>
      </div>

      <p class='mb-3'><strong><%= @user.public_name %></strong></p>

      <div class='user-data-display mb-3'>
        <div id='following-count'>
          <%= render 'admin/relationships/links', user: @user %>
        </div>
        <%= render 'public/users/count', user: @user %>
      </div>

      <p class='mb-3'>
        <%= I18n.t('users.show.position_start') %>
        <span class=<%= @user.get_class_associated_with_position %>><!--positionによって違うcss-->
          <%= @user.position_i18n %>
        </span>
        <%= I18n.t('users.show.position_end') %>
      </p>

      <p class='mb-5'><%= @user.introduction %></p>
      <hr>
    </div>

    <div class='col-md-8'>
      <!--検索バー-->
      <%= form_with url: admin_user_path(@user.canonical_name), method: :get, local: true do |f| %>
        <div class='row justify-content-md-end justify-content-center'>
          <div class='form-group col-md-5 col-10 mb-1'>
            <%= f.select :prefecture, Post.prefectures.keys.map {|k| [I18n.t("enums.post.prefecture.#{k}"), k]}, selected: @prefecture, class: 'form-control' %>
            <%= f.select :sort, [[I18n.t('sort.latest'), 'latest'],[I18n.t('sort.old'), 'old'],[I18n.t('sort.favorites_count'), 'favorites_count']], selected: @sort, class: 'form-control ml-1' %>
          </div>
        </div>
        <div class='row justify-content-md-end justify-content-center'>
          <div class='form-group col-md-5 col-9'>
            <%= f.text_field :keyword, value: @keyword, class: 'form-control', placeholder: I18n.t('search_blank') %>
          </div>
          <div class='form-group mt-1'>
            <%= f.submit I18n.t('search'), class: 'btn btn-sm success-btn' %>
          </div>
        </div>
      <% end %>

      <!--ソート切り替えリンク-->
      <p class='md-font text-center mb-0'><%= I18n.t('sort.with_display_all') %></p>
      <div class='text-center pb-2'>
      <%= link_to I18n.t('sort.latest'), admin_user_path(@user.canonical_name, sort: 'latest') %>
      |<%= link_to I18n.t('sort.old'), admin_user_path(@user.canonical_name, sort: 'old') %>
      |<%= link_to I18n.t('sort.favorites_count'), admin_user_path(@user.canonical_name, sort: 'favorites_count') %>
      </div>

      <!--ユーザーの投稿一覧表示-->
      <%= render 'admin/posts/index', posts: @posts %>
    </div>

  </div>
</section>

<%= javascript_pack_tag 'image_expansion' %>